services:
  develop:
    build: .
    ports:
      - "3000:3000"
    container_name: fw-exports-develop
    environment:
      PORT: 3000
      AUTH_URL: https://staging-api.resourcewatch.org
      FORMS_API_URL: https://api.resourcewatch.org/v1
      AREAS_API_URL: "https://dev-fw-api.globalforestwatch.org/v3/forest-watcher"
      ALERTS_API_URL: "https://staging-data-api.globalforestwatch.org"
      GFW_DATA_API_KEY: ${gfw_data_api_key}
      S3_ACCESS_KEY_ID: ${myS3Key}
      S3_SECRET_ACCESS_KEY: ${myS3Secret}
    volumes:
      - ./app:/opt/fw-exports/app
      - ./config:/opt/fw-exports/config
      - ./nodemon.json:/opt/fw-exports/nodemon.json
    command: yarn dev

  test:
    build: .
    container_name: fw-exports-test
    environment: 
      AREAS_API_URL: http://127.0.0.1:9000
    volumes:
      - ./app:/opt/fw-exports/app
      - ./config:/opt/fw-exports/config
      - ./nodemon.json:/opt/fw-exports/nodemon.json
      - ./jest.config.js:/opt/fw-exports/jest.config.js
    command: yarn test

  docs:
    build: .
    ports:
      - "30000:30000"
    container_name: fw-exports-docs
    volumes:
      - ./docs:/opt/fw-exports/docs
    command: yarn run docs -l 30000