name: Plan terraform changes for base branch

on: [pull_request]

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Grant Permission
      run: |
        chmod +x ./scripts/*
    - name: Plan production
      if: github.base_ref == 'production'
      env:
        ENV: production
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_production }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_production }}
        AWS_REGION: ${{ secrets.aws_region_production }}
        EXPORTS_S3_ACCESS_KEY_ID: ${{ secrets.exports_s3_access_key_id }}
        EXPORTS_S3_SECRET_ACCESS_KEY: ${{ secrets.exports_s3_secret_access_key }}
        SPARKPOST_API_KEY: ${{ secrets.SPARKPOST_API_KEY }}
      run: ./scripts/infra plan -var "s3_access_key_id=${EXPORTS_S3_ACCESS_KEY_ID}" \
                                -var "s3_secret_access_key=${EXPORTS_S3_SECRET_ACCESS_KEY}" \
                                -var "SPARKPOST_API_KEY"=${SPARKPOST_API_KEY}
    - name: Plan staging
      if: github.base_ref == 'staging'
      env:
        ENV: staging
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_staging }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_staging }}
        AWS_REGION: ${{ secrets.aws_region_staging }}
        EXPORTS_S3_ACCESS_KEY_ID: ${{ secrets.exports_s3_access_key_id }}
        EXPORTS_S3_SECRET_ACCESS_KEY: ${{ secrets.exports_s3_secret_access_key }}
        SPARKPOST_API_KEY: ${{ secrets.SPARKPOST_API_KEY }}
      run: ./scripts/infra plan -var "s3_access_key_id=${EXPORTS_S3_ACCESS_KEY_ID}" \
                                -var "s3_secret_access_key=${EXPORTS_S3_SECRET_ACCESS_KEY}" \
                                -var "SPARKPOST_API_KEY=${SPARKPOST_API_KEY}"
    - name: Plan dev
      if: github.base_ref == 'dev'
      env:
        ENV: dev
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_dev }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_dev }}
        AWS_REGION: ${{ secrets.aws_region_dev }}
        EXPORTS_S3_ACCESS_KEY_ID: ${{ secrets.exports_s3_access_key_id }}
        EXPORTS_S3_SECRET_ACCESS_KEY: ${{ secrets.exports_s3_secret_access_key }}
        SPARKPOST_API_KEY: ${{ secrets.SPARKPOST_API_KEY }}
      run: "./scripts/infra plan -var \"s3_access_key_id=${EXPORTS_S3_ACCESS_KEY_ID}\"
                                -var \"s3_secret_access_key=${EXPORTS_S3_SECRET_ACCESS_KEY}\" 
                                -var \"SPARKPOST_API_KEY=${SPARKPOST_API_KEY}\""